// apps/angular/src/app/app.component.ts
import { Component } from '@angular/core';

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.css'],
})
export class AppComponent {
  generateRandomArray() {
    const arrayLength = 20;
    return Array.from({ length: arrayLength }, () =>
      Math.floor(Math.random() * 100)
    );
  }

  width = 200;
  height = 50;
  lineColor = '#2220a4';
  bgColor = '#191919';
  serie = this.generateRandomArray();
}

<div class="controls">
  <label for="width-range">Width</label>
  <input
    type="range"
    name="height-range"
    id="width-range"
    min="100"
    max="300"
    [(ngModel)]="width"
  />
  <label for="height-range">Height</label>
  <input
    type="range"
    name="height-range"
    id="height-range"
    min="40"
    max="150"
    [(ngModel)]="height"
  />
  <label for="bg-color">Background color: </label>
  <input id="bg-color" type="color" [(ngModel)]="bgColor" />
  <label for="line-color">Line color: </label>
  <input id="line-color" type="color" [(ngModel)]="lineColor" />
  <input
    type="button"
    (click)="serie = generateRandomArray()"
    value="Generate data"
  />
</div>
<chart-card
  class="balance-card"
  [serie]="serie"
  [attr.background-color]="bgColor"
  [attr.line-color]="lineColor"
  [attr.chart-width]="width"
  [attr.chart-height]="height"
>
  <h2 class="balance-card__title">Balance:</h2>
  <div class="balance-card__amount">15 €</div>
</chart-card>

// apps/reactjs/src/App.tsx
import { useMemo, useState } from 'react'
import './App.css'

function generateRandomArray(): number[] {
  const arrayLength = 20;
  return Array.from({ length: arrayLength }, () =>
    Math.floor(Math.random() * 100)
  );
}

function App() {
  const [serie, setSerie] = useState<number[]>(generateRandomArray());
  const [bgColor, setBgColor] = useState("#191919")
  const [lineColor, setLineColor] = useState("#2220a4")
  const [width, setWidth] = useState<number | string>(200);
  const [height, setHeight] = useState<number | string>(50);

  const balance = useMemo(() => {
    const length = serie.length;
    return length > 0 ? serie[length - 1] : 0;
  }, [serie])

  return (
    <div className="App">
      <div className="controls">
        <label htmlFor="width-range">Width</label>
        <input
          type="range"
          name="height-range"
          id="width-range"
          min="100"
          max="300"
          value={width}
          onChange={(e) => setWidth(e.target.value)}
        />
        <label htmlFor="height-range">Height</label>
        <input
          type="range"
          name="height-range"
          id="height-range"
          min="40"
          max="150"
          value={height}
          onChange={(e) => setHeight(e.target.value)}
        />
        <label htmlFor="bg-color">Background color: </label>
        <input id="bg-color" type="color" value={bgColor} onChange={(e) => setBgColor(e.target.value)} />
        <label htmlFor="line-color">Line color: </label>
        <input id="line-color" type="color" value={lineColor} onChange={(e) => setLineColor(e.target.value)} />
        <input
          type="button"
          onClick={() => setSerie(generateRandomArray())}
          value="Generate data"
        />
      </div>
      <chart-card
        className="balance-card"
        serie={serie}
        background-color={bgColor}
        line-color={lineColor}
        chart-width={width}
        chart-height={height}
      >
        <h2 className="balance-card__title">Balance:</h2>
        <div className="balance-card__amount">{balance} €</div>
      </chart-card>
      <vue-chart-card
        className="balance-card"
        serie={serie}
        background-color={bgColor}
        line-color={lineColor}
        chart-width={width}
        chart-height={height}
      >
        <h2 className="balance-card__title">Balance:</h2>
        <div className="balance-card__amount">{balance} €</div>
      </vue-chart-card>
    </div>
  )
}

export default App
