// apps/angular/src/main.ts
import { enableProdMode } from '@angular/core';
import { platformBrowserDynamic } from '@angular/platform-browser-dynamic';

import { AppModule } from './app/app.module';
import { environment } from './environments/environment';

import { ChartCard } from '@bsyoann/chartcard';
// @ts-ignore
import { VueChartCard } from '../../../libs/vuechartcard/dist/index.es.js';

customElements.define('chart-card', ChartCard);
customElements.define('vue-chart-card', VueChartCard);

if (environment.production) {
  enableProdMode();
}

platformBrowserDynamic()
  .bootstrapModule(AppModule)
  .catch((err) => console.error(err));

// apps/reactjs/src/main.tsx
import React from 'react'
import ReactDOM from 'react-dom'
import './index.css'
import App from './App'

import { ChartCard } from '@bsyoann/chartcard';
import { VueChartCard, VueTest } from '../../../libs/vuechartcard/dist/index.es.js';

console.log(VueChartCard);

customElements.define("chart-card", ChartCard);
// customElements.define("vue-chart-card", VueChartCard);
customElements.define("vue-test", VueTest);

ReactDOM.render(
  <React.StrictMode>
    <App />
  </React.StrictMode>,
  document.getElementById('root')
)
